### PR TITLE
fix(vike-solid-query): fix `No QueryClient set` & `<QueryBoundary>`

### LINKED ISSUE #123: [vike-solid-query] No QueryClient set, use QueryClientProvider to set one
Created home page from [examples/solid-query](https://github.com/vikejs/vike-solid/tree/main/examples/solid-query).

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-elysia-solid-daisyui.git`
2. `cd template-vike-elysia-solid-daisyui`
3. `git test-solid-query`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000`

## Output
```console
  VITE v5.4.5  ready in 1052 ms
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
8:11:36 PM [vike][request(1)] HTTP request: /

🌼   daisyUI 4.12.10
├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

8:11:37 PM [vike][request(1)] Following error was thrown by the onRenderHtml() hook defined at vike-solid/__internal/integration/onRenderHtml
15 |   if (queryClient) {
16 |     return queryClient;
17 |   }
18 |   const client = useContext(QueryClientContext);
19 |   if (!client) {
20 |     throw new Error("No QueryClient set, use QueryClientProvider to set one");
              ^
error: No QueryClient set, use QueryClientProvider to set one
      at useQueryClient (C:\template-vike-elysia-solid-daisyui\node_modules\@tanstack\solid-query\build\dev.js:20:10)
      at createMemo (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:97:10)
      at createBaseQuery (C:\template-vike-elysia-solid-daisyui\node_modules\@tanstack\solid-query\build\dev.js:194:11)
      at Movies (unknown:25:50)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at Page (unknown:17:322)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at renderWrappers (C:\template-vike-elysia-solid-daisyui\node_modules\vike-solid\dist\integration\onRenderHtml.js:72:4)
      at children (unknown:32:19)
      at Content (unknown:20:173)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at Layout (unknown:30:74)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at createComponent (C:\template-vike-elysia-solid-daisyui\node_modules\solid-js\dist\server.js:359:10)
      at children (C:\template-vike-elysia-solid-daisyui\node_modules\vike-solid\dist\hooks\usePageContext.js:12:7)

8:11:37 PM [vike][request(1)] HTTP response / 500
```

## Notes
- Bun is used
- Similar #124

### LINKED ISSUE #124: [vike-solid-query] Qualified path resolution failed: we looked for the following paths, but none could be accessed
Created home page from [examples/solid-query](https://github.com/vikejs/vike-solid/tree/main/examples/solid-query).

## Reproduction
1. `git clone https://github.com/rtritto/template-vike-solid-daisyui.git`
2. `cd template-vike-solid-daisyui`
3. `git test-solid-query`
4. `yarn`
5. `yarn dev`
6. Navigate to `http://localhost:3000`

## Output
```console
  VITE v5.4.5  ready in 2117 ms
  ➜  Local:   http://localhost:3000/
  ➜  Network: use --host to expose
  ➜  press h + enter to show help
20:35:21 [vike][request(1)] HTTP request: /

🌼   daisyUI 4.12.10
├─ ✔︎ 1 theme added             https://daisyui.com/docs/themes
╰─ ❤︎ Support daisyUI project:  https://opencollective.com/daisyui

20:35:22 [vike][request(1)][Error] Transpilation error:
Error: Qualified path resolution failed: we looked for the following paths, but none could be accessed.

Source path: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\<USER>\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary
Not found: C:\template-vike-solid-daisyui\.yarn\__virtual__\vike-solid-query-virtual-5e8ba09589\3\Users\<USER>\AppData\Local\Yarn\Berry\cache\vike-solid-query-npm-0.0.1-37c4e8e89f-10c0.zip\node_modules\vike-solid-query\dist\src\QueryBoundary

    at makeError (C:\template-vike-solid-daisyui\.pnp.cjs:12259:34)
    at resolveUnqualified (C:\template-vike-solid-daisyui\.pnp.cjs:13991:13)
    at resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14031:14)
    at Object.resolveRequest (C:\template-vike-solid-daisyui\.pnp.cjs:14087:26)
    at resolve$1 (file:///C:/template-vike-solid-daisyui/.pnp.loader.mjs:2043:21)
    at nextResolve (node:internal/modules/esm/hooks:750:28)
    at Hooks.resolve (node:internal/modules/esm/hooks:238:30)
    at handleMessage (node:internal/modules/esm/worker:199:24)
    at checkForMessages (node:internal/modules/esm/worker:141:28)
    at process.<anonymous> (node:internal/modules/esm/worker:160:5)
┌──────────────────────────────────────────────────────────┐
│ Error isn't helpful? See https://vike.dev/errors#verbose │
└──────────────────────────────────────────────────────────┘
20:35:22 [vike][request(1)] HTTP response / 500
```

## Notes
- Yarn with PnP (Plug'n'Play) is used
- Similar #123

### PR DESCRIPTION
**Pull request by phonzammi**
fix #123 
fix #124 

Regarding the `<QueryBoundary>` bug, I think it looks good to me in this commit.

The current release of `vike-solid-query` is compatible with `examples/solid-query` only within the `vike-solid` repository, and not for use outside of it.

## `No QueryClient set` bug
I've been working to make it functional for both use cases and have identified two potential approaches, but neither is perfect:
1. First approach : build `Wrapper.tsx` to `Wrapper.jsx` using tsc
This works for both `examples/solid-query` and other use cases, but there is a warning :
```js
Cannot optimize dependency: vike-solid-query/__internal/integration/Wrapper, present in 'optimizeDeps.include'
```
Please try pre-released as : `0.0.1-commit-21483db`
 
2. The second approach : Build everything using rollup

~~Both is wip, I need more try, and I need help :pray:~~

I believe it should be fixed by adding these export conditions in the `package.json`:
```json
"./integration/Wrapper": {
  "solid": "./dist/integration/Wrapper.js", // this one is the fix
  "import": {
    "types": "./dist/integration/Wrapper.d.ts",
    "default": "./dist/integration/Wrapper.js"
  }
}
```

### CODE REVIEW

**Comment by rtritto** [comment]
I did a try installing `0.0.1-commit-21483db` version but always `0.0.1` version is used:

```diff
// yarn.lock

- "vike-solid-query@npm:^0.0.1":
+ "vike-solid-query@npm:^0.0.1-commit-21483db":
  version: 0.0.1
  resolution: "vike-solid-query@npm:0.0.1"
  peerDependencies:
    "@tanstack/solid-query": ">=5.0.0"
    solid-js: ^1.8.7
    vike-solid: ">=0.7.3"
  checksum: 10c0/bb3c50b022933d845096619351b659544eb8fa79fd8b905a0363228f32d9bf2362bf82332f488b12dfcb91b5ede3f04dbfb164aa0238cf916eab3b10aa32d6bb
  languageName: node
  linkType: hard
```

**Comment by brillout** [comment]
@rtritto That is a Yarn question. Have a look at and please respect https://brillout.github.io/rules/ (I believe I sent you this already). Thanks!

**Comment by rtritto** [comment]
> @rtritto That is a Yarn question. Have a look at and please respect https://brillout.github.io/rules/ (I believe I sent you this already). Thanks!

My bad, I correctly installed `0.0.1-commit-21483db` and the issue has been fixed, thanks.

**Comment by phonzammi** [comment]
2. The second approach : Build everything using rollup, commit https://github.com/vikejs/vike-solid/pull/127/commits/01e0751044af5a8179e07b9ff24b97863a1aed11

This approach works outside of `vike-solid` repo, the `examples/solid-query` will throws errors:
@brillout, Please take a look at this error
```js
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
vvvvvv ERROR & WARNING LOGS vvvvvv
vvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvvv
[13:06:10.962][\examples\solid-query][pnpm run dev][stderr] 1:06:10 PM [vike@0.4.196][config][Bug] You stumbled upon a Vike bug. Go to https://github.com/vikejs/vike/issues/new and copy-paste this error. A maintainer will fix the bug (usually under 24 hours).
    at resolvePointerImport (file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.32.0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/resolvePointerImport.js:43:9)
    at resolvePointerImportOfConfig (file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.32.0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig/resolvePointerImport.js:17:22)
    at getConfigValueSource (file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.32.0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:576:[31](https://github.com/vikejs/vike-solid/actions/runs/11033624719/job/30645205771?pr=127#step:8:32))
    at file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.32.0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:507:77
    at Array.map (<anonymous>)
    at resolveConfigValueSources (file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.[32](https://github.com/vikejs/vike-solid/actions/runs/11033624719/job/30645205771?pr=127#step:8:33).0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:507:51)
    at file:///D:/a/vike-solid/vike-solid/node_modules/.pnpm/vike@0.4.196_vite@5.4.7_@types+node@22.5.5_terser@5.32.0_/node_modules/vike/dist/esm/node/plugin/plugins/importUserCode/v1-design/getVikeConfig.js:267:35
    at Array.map (<anonymous>)
```

@rtritto, also try this pre-released as `0.0.1-commit-01e0751`

**Comment by rtritto** [comment]
With `0.0.1-commit-01e0751`, at Vike start:

```console
3:35:59 PM [vike][config][Wrong Usage] The import import:./Wrapper.js:default defined in vike-solid-query/config couldn't be resolved: does './Wrapper.js' point to an existing file?
```

**Comment by phonzammi** [comment]
Have you tried cleaning your repo first?

**Comment by rtritto** [comment]
> Have you tried cleaning your repo first?

Yes

**Comment by phonzammi** [comment]
Hmm, I tested your repo (https://github.com/rtritto/template-vike-elysia-solid-daisyui/tree/test-solid-query), and it seems like it doesn't work with `bun --bun vite`, but it does work with `vite`.

**Comment by brillout** [comment]
@phonzammi Thank you for the ping and, indeed, I could reproduce. I'll fix it later today.

> Hmm, I tested your repo (https://github.com/rtritto/template-vike-elysia-solid-daisyui/tree/test-solid-query), and it seems like it doesn't work with `bun --bun vite`, but it does work with `vite`.

@rtritto Please double, triple, quadruple check whether it's a Vike issue or not before pinging us. It makes a big difference for us. As you can imagine, we've a *lot* of things to do, so anything that saves us time is a big help for us. Thank you! Looking forward to your future issues :eyes:

**Comment by brillout** [comment]
> @phonzammi Thank you for the ping and, indeed, I could reproduce. I'll fix it later today.

Done (https://github.com/vikejs/vike/commit/11810cf377b3e7bd1d705e9487efd28cbd295c84). You'll get a proper error message in the next release. You cannot use relative imports like you're trying (because of a Vite limitation).

**Comment by phonzammi** [comment]
I think it should be fixed now.

@rtritto, please try this Pre-released as `0.0.1-commit-6abb0a2`

**Comment by rtritto** [comment]
With `0.0.1-commit-6abb0a2`, I have no errors on imports (Bun and Node.js).
Thanks!

**Comment by phonzammi** [comment]
We're glad to know it works now!

LGTM then :rocket:

**Comment by magne4000** [comment]
I'm doing the review tomorrow

**Comment by magne4000** [comment]
LGTM.

`solid` plugin bundling is really not on point. I would prefer that they would have official support for esbuild, and auto target generation for ssr/non-ssr files.

**Comment by magne4000** [comment]
@phonzammi You have to publish the new release, I do not have the accesses on npm for `vike-solid-query`

**Comment by magne4000** [comment]
Also, publish it as `0.1.0` as every `0.0.x` version is considered a _breaking change_ in semver.

**Comment by phonzammi** [comment]
Thank you.

Released as `0.1.0`

**Comment by magne4000** [comment]
> `solid` plugin bundling is really not on point. I would prefer that they would have official support for esbuild, and auto target generation for ssr/non-ssr files.

@phonzammi just pointed out to me that https://github.com/solidjs-community/tsup-preset-solid exists. We need to try it!

**Comment by rtritto** [comment]
> @phonzammi just pointed out to me that https://github.com/solidjs-community/tsup-preset-solid exists. We need to try it!

Agree, `tsup` should be fast, powerful and simple.

I started using yesterday and did https://github.com/elysiajs/node-adapter/pull/4 (maybe can help).

**Pull request merged**
