### PR TITLE
chore: refactor

### PR DESCRIPTION
**Pull request by phonzammi**

### CODE REVIEW

**Comment by magne4000** [comment]
We should also include the following:
[As suggested](https://github.com/vikejs/vike-solid/pull/90#issuecomment-2178210598) by @brillout:
- [ ] Update migration
- [ ] Use [@brillout/release-me](https://github.com/brillout/release-me)

**Comment by phonzammi** [comment]
@magne4000, @brillout 
I've added `@brillout/release-me`. Please take a look to verify.

Regarding updating migration, I'm not sure what needs to be added. :pray:

**Comment by phonzammi** [comment]
Should we add `e2e-tests`, `prettier`, and `biome` (possibly in a separate PR) ?

**Comment by magne4000** [comment]
@phonzammi I'll take care of migration and making sure that the release flow is correct.

> Should we add e2e-tests, prettier, and biome (possibly in a separate PR) ?

Would be great to have all of it yes (and yes in another PR)

**Pull request merged**
