### PR TITLE
feat: ClientOnly component

### LINKED ISSUE #36: `<ClientOnly>` Component
Since `vike-react` now has a [`<ClientOnly>` component](https://github.com/vikejs/vike-react/pull/35), it would be great to align `vike-solid` to also have such component.

### PR DESCRIPTION
**Pull request by magne4000**
Same as https://github.com/vikejs/vike-react/pull/35 but for Solid.

Closes #36

### Usage

```tsx
import { createSignal } from "solid-js";
import { ClientOnly } from "vike-solid/ClientOnly";

export { Counter };

function Counter() {
  const [count, setCount] = createSignal(0);

  return (
    <>
      <button onClick={() => setCount((count) => count + 1)}>
        Counter {count()}
      </button>
      <ClientOnly load={() => import('../star-wars/index/+Page')}>
        {(Page) => <Page movies={[{ id: '1', title: `${count()}`, release_date: 'today' }]} />}
      </ClientOnly>
    </>
  );
}

```

### CODE REVIEW

**Comment by brillout** [comment]
Very neat 🚀

I wonder, do we need `deps` in Solid?

Other than `deps`, the interface is exactly the same, correct? Context: https://github.com/vikejs/vike/pull/1289.

**Comment by brillout** [comment]
FYI @usk94

**Comment by magne4000** [comment]
> I wonder, do we need deps in Solid?

We do not, thanks to how Solid works internally :rocket:.

**Comment by magne4000** [comment]
> Other than deps, the interface is exactly the same, correct? Context: https://github.com/vikejs/vike/pull/1289.

And yes, almost a copy paste, so no difference beside not needing deps.

**Pull request merged**
