### PR TITLE
fix: simplify `<head>` management

### PR DESCRIPTION
**Pull request by AurelienLourot**
See also:
https://github.com/vikejs/vike-react/pull/70
https://github.com/vikejs/vike-vue/pull/70

### BREAKING CHANGES

* Fetching data using `pageContext.pageProps` is deprecated, use `data()` and `useData()` instead, see https://vike.dev/data-fetching
* Setting the page's title using `pageContext.title` is deprecated (`pageContext.description` and `pageContext.lang` are also deprecated), use the settings `title` and `Head` instead, see https://vike.dev/head

### CODE REVIEW

**Comment by AurelienLourot** [comment]
Holding off a bit. I now believe we shouldn't remove the `description` setting. See https://github.com/vikejs/vike-vue/issues/73#issuecomment-1907004814

**Comment by AurelienLourot** [comment]
Discussion settled. I'm happy again with this PR

**Comment by magne4000** [comment]
I like that we can have even less code to write the same thing :)
LGTM!

**Comment by magne4000** [comment]
I'll publish a new release after merging dependencies upgrade :+1:

**Comment by magne4000** [comment]
@AurelienLourot I'm currently applying the migration to Bati

**Comment by AurelienLourot** [comment]
Thanks a lot :pray:

**Pull request merged**
